#db config
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demo_app"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false